version: '3.3'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--sort_buffer_size=1073741824"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=twitter_snapshot
      - MYSQL_USER=runner
      - MYSQL_PASSWORD=runner
    ports:
      - '33069:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
